# Generated by Django 2.2.4 on 2019-09-02 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +7(999) 999-99-99', regex='\\+\\d{1,3}\\(\\d{3}\\) \\d{3}-\\d\\d-\\d\\d')])),
            ],
        ),
    ]
