# Generated by Django 2.2.4 on 2019-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190902_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='name',
            field=models.CharField(default='noname', max_length=25, verbose_name='Имя пользователя'),
        ),
    ]
