# Generated by Django 2.2.4 on 2019-09-02 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате +7(999) 999-99-99, +77(999) 999-99-99 или +777(999) 999-99-99', regex='^\\+\\d{1,3}\\(\\d{3}\\) \\d{3}-\\d\\d-\\d\\d$')], verbose_name='Номер телефона'),
        ),
    ]
