# Generated by Django 2.2.4 on 2019-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения пользователя'),
        ),
    ]
